CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;
CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);
CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);

select * from customers;
select * from order_items;
select * from orders;
select * from products;

-- PART 1: Customer & Inventory Filtering
--  Business Requirement: The marketing and inventory teams want to identify customer acquisition trends and inventory risks.

-- Q1. Show all customers from Bengaluru.
select  * from customers
where city='Bengaluru';

-- Q2. Show customers who signed up after ‘2025-01-01’.
select * from customers
where signup_date>'2025-01-01';

-- Q3. Find customers from Mumbai and Hyderabad.
select * from customers
where city in ("Mumbai","Hyderabad");

-- Q4. Show products belonging to the Electronics category.
select * from products 
where category="Electronics";

-- Q5. Find products priced above 40000.
select * from products 
where price>40000;

-- Q6. Show products where stock is less than 20.
select * from products 
where stock<20;

-- Q7. Find products with stock between 50 and 100.
select * from products
where stock between 50 and 100;

-- Q8. Show customers whose names start with ‘A’.
select * from customers 
where customer_name like'A%';

-- Q9. Find products whose names contain ‘Premium’.
select * from products 
where product_name like "%Premium%";

-- Q10. Show customers registered during the year 2025.
select * from customers where year(signup_date)=2025;

select * from customers;
select * from order_items;
select * from orders;
select * from products;

-- PART 2: Revenue & Sales Analysis
-- Business Requirement: The finance department wants summarized revenue and sales insights.

-- Q11. Find total revenue generated by each category.
select category, sum(price) as revenue
from products
group by category
order by revenue desc
limit 5;

-- Q12. Find total quantity sold for each product.
select product_id,sum(quantity) as total_quantity
from order_items
group by product_id;

-- Q13. Find total orders under each order status.
select status, count(order_id)
from orders
group by status;

-- Q14. Find total revenue generated through each payment method.
select o.payment_method, sum(p.price) as total_revenue
from orders o 
join order_items oi on o.order_id=oi.order_id
join products p on oi.product_id=p.product_id
group by o.payment_method
order by total_revenue
limit 5;

-- Q15. Find average product price category-wise.
 
select  category ,avg(price) as average_price
from products
group by category;

-- Q16. Find category-wise quantity sold.
select p.category, sum(oi.quantity) as Quantity
from products p 
join order_items oi on p.product_id=oi.product_id
group by p.category;

-- Q17. Find monthly order count.
select month(order_date) as month1, count(order_id) as total_orders
from orders
group by month1;

-- Q18. Find monthly revenue trend.
select month(o.order_date) as month1, sum(oi.quantity*oi.unit_price) as revenue
from orders o 
join order_items oi on o.order_id=oi.order_id
group by month1;

-- Q19. Find the most commonly used payment method.
select payment_method, count(customer_id) as common_payment
from orders 
group by payment_method;

-- Q20. Find the highest revenue-generating category.
select category, sum(price) as highest_revenue
from products 
group by category
order by highest_revenue
limit 1;

-- PART 3: High-Value Business Insights
-- Business Requirement: Management wants to identify high-performing customers, products, and regions.

select * from customers;
select * from order_items;
select * from orders;
select * from products;

-- Q21. Find customers who placed more than 5 orders.
select c.customer_name,count(o.order_id) as total_count
from customers c
join orders o on c.customer_id=o.customer_id
group by c.Customer_ID
having count(o.Order_ID)>5;

-- Q22. Find top 5 customers based on total spending.
select c.customer_name, sum(oi.quantity*oi.unit_price)total_spending
from customers c
join orders o on c.customer_id=o.customer_id
join order_items oi  on o.order_id=oi.order_id
group by c.customer_name
order by total_spending desc
limit 5;




