CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;
CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);
CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);

select * from customers;
select * from order_items;
select * from orders;
select * from products;

-- PART 1: Customer & Inventory Filtering
--  Business Requirement: The marketing and inventory teams want to identify customer acquisition trends and inventory risks.

-- Q1. Show all customers from Bengaluru.
select  * from customers
where city='Bengaluru';

-- Q2. Show customers who signed up after ‘2025-01-01’.
select * from customers
where signup_date>'2025-01-01';

-- Q3. Find customers from Mumbai and Hyderabad.
select * from customers
where city in ("Mumbai","Hyderabad");

-- Q4. Show products belonging to the Electronics category.
select * from products 
where category="Electronics";

-- Q5. Find products priced above 40000.
select * from products 
where price>40000;

-- Q6. Show products where stock is less than 20.
select * from products 
where stock<20;

-- Q7. Find products with stock between 50 and 100.
select * from products
where stock between 50 and 100;

-- Q8. Show customers whose names start with ‘A’.
select * from customers 
where customer_name like'A%';

-- Q9. Find products whose names contain ‘Premium’.
select * from products 
where product_name like "%Premium%";

-- Q10. Show customers registered during the year 2025.
select * from customers where year(signup_date)=2025;

select * from customers;
select * from order_items;
select * from orders;
select * from products;

-- PART 2: Revenue & Sales Analysis
-- Business Requirement: The finance department wants summarized revenue and sales insights.

-- Q11. Find total revenue generated by each category.
select category, sum(price) as revenue
from products
group by category
order by revenue desc
limit 5;

-- Q12. Find total quantity sold for each product.
select product_id,sum(quantity) as total_quantity
from order_items
group by product_id;

-- Q13. Find total orders under each order status.
select status, count(order_id)
from orders
group by status;

-- Q14. Find total revenue generated through each payment method.
select o.payment_method, sum(p.price) as total_revenue
from orders o 
join order_items oi on o.order_id=oi.order_id
join products p on oi.product_id=p.product_id
group by o.payment_method
order by total_revenue
limit 5;

-- Q15. Find average product price category-wise.
 
select  category ,avg(price) as average_price
from products
group by category;

-- Q16. Find category-wise quantity sold.
select p.category, sum(oi.quantity) as Quantity
from products p 
join order_items oi on p.product_id=oi.product_id
group by p.category;

-- Q17. Find monthly order count.
select month(order_date) as month1, count(order_id) as total_orders
from orders
group by month1;

-- Q18. Find monthly revenue trend.
select month(o.order_date) as month1, sum(oi.quantity*oi.unit_price) as revenue
from orders o 
join order_items oi on o.order_id=oi.order_id
group by month1;

-- Q19. Find the most commonly used payment method.
select payment_method, count(customer_id) as common_payment
from orders 
group by payment_method;

-- Q20. Find the highest revenue-generating category.
select category, sum(price) as highest_revenue
from products 
group by category
order by highest_revenue
limit 1;

-- PART 3: High-Value Business Insights
-- Business Requirement: Management wants to identify high-performing customers, products, and regions.

select * from customers;
select * from order_items;
select * from orders;
select * from products;

-- Q21. Find customers who placed more than 5 orders.
select c.customer_name,count(o.order_id) as total_count
from customers c
join orders o on c.customer_id=o.customer_id
group by c.Customer_ID
having count(o.Order_ID)>5;

-- Q22. Find top 5 customers based on total spending.
select c.customer_name, sum(oi.quantity*oi.unit_price)total_spending
from customers c
join orders o on c.customer_id=o.customer_id
join order_items oi  on o.order_id=oi.order_id
group by c.customer_name
order by total_spending desc
limit 5;

-- Q23. Find products sold more than 30 times.
select p.product_name, count(oi.order_id) as total_sold
from products p 
join order_items oi on p.product_id=oi.product_id
group by p.Product_Name
having count(oi.order_id) >30;

-- Q24. Find categories generating revenue greater than 500000.
select p.category, sum(oi.quantity*oi.unit_price) as revenue
from products p 
join order_items oi on p.Product_ID=oi.Product_ID
group by p.Category
having revenue>500000;

-- Q25. Find cities having more than 10 customers.
select city,count(customer_id) as count_cust
from customers 
group by city
having count_cust>10;

-- Q26. Find the top 5 highest-selling products.
select p.product_name, count(oi.order_id) as high_selling
from products p 
join order_items oi on p.Product_ID=oi.Product_ID
group by p.Product_Name 
order by high_selling desc
limit 5; 

-- Q27. Find the top 3 most profitable products.
SELECT p.product_name,
       SUM(oi.quantity * oi.unit_price) AS total_profit
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_profit DESC
LIMIT 3;

-- Q28. Find customers whose spending is above average customer spending.

SELECT c.customer_id,
       c.customer_name,
       SUM(oi.quantity * oi.unit_price) AS total_spending
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name
HAVING SUM(oi.quantity * oi.unit_price) >
(
    SELECT AVG(customer_spending)
    FROM
    (
        SELECT SUM(oi.quantity * oi.unit_price) AS customer_spending
        FROM orders o
        JOIN order_items oi
        ON o.order_id = oi.order_id
        GROUP BY o.customer_id
    ) avg_table
);
-- Q29. Find products contributing more than 10% of company revenue.

SELECT p.product_name,
       SUM(oi.quantity * oi.unit_price) AS product_revenue
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.product_name
HAVING SUM(oi.quantity * oi.unit_price) >
(
    SELECT 0.10 * SUM(quantity * unit_price)
    FROM order_items
);

-- Q30. Find the city generating the highest revenue.

SELECT c.city,
       SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.city
ORDER BY total_revenue DESC
LIMIT 1;

-- PART 4: Customer & Product Intelligence
-- Business Requirement: The CRM and product teams want detailed operational insights.

select * from customers;
select * from order_items;
select * from orders;
select * from products;

-- Q31. Display all orders along with customer names.
select o.order_id, c.Customer_ID,c.customer_name,o.order_date,o.status,o.Payment_Method
from orders o
join customers c  on o.Customer_ID=c.Customer_ID;
 
 -- cte
 with cte1 as (select o.order_id, c.Customer_ID,c.customer_name,o.order_date,o.status,o.Payment_Method
from orders o
join customers c  on o.Customer_ID=c.Customer_ID
where Payment_Method="Credit Card"
)
select * from cte1;

-- view
create view view1 as
select o.order_id, c.Customer_ID,c.customer_name,o.order_date,o.status,o.Payment_Method
from orders o
join customers c  on o.Customer_ID=c.Customer_ID
where Payment_Method="UPI";

-- stored procedure
delimiter $$
create procedure get_cust_name()
begin
select o.order_id, c.Customer_ID,c.customer_name,o.order_date,o.status,o.Payment_Method
from orders o
join customers c  on o.Customer_ID=c.Customer_ID;
end
$$ delimiter ;

 call get_cust_name();
 
 -- Q32. Find total revenue generated by each customer.
select  c.customer_id,c.customer_name,SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name;

delimiter $$
create procedure rev_by_cust(out revenue int)
begin 
select  c.customer_id,c.customer_name,SUM(oi.quantity * oi.unit_price) as revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name;
end
$$ delimiter ;
set @total=0;
call rev_by_cust(@total);
select @total;

-- out can only store single variable , but here i tried to store multiple values in sinhle out variable "revenue

-- Q40. Find repeat customers who ordered in multiple months.

select count(distinct extract(year_month from order_date)) -- gives count of combo of year and month in a 2025/year
from orders;

select count(distinct concat(year(order_date),'-',month(order_date))) as active_months
from orders; -- same as above

SELECT customer_id,
       COUNT(DISTINCT CONCAT(YEAR(order_date),'-',MONTH(order_date))) AS active_months
FROM orders
GROUP BY customer_id
HAVING active_months > 1;
-- or
SELECT customer_id,
       COUNT(DISTINCT DATE_FORMAT(order_date,'%Y-%m')) AS active_months
FROM orders
GROUP BY customer_id
HAVING active_months > 1
order by active_months desc; 
-- or
SELECT c.customer_name,
       COUNT(DISTINCT DATE_FORMAT(o.order_date,'%Y-%m')) AS active_months
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING active_months > 1
ORDER BY active_months DESC;

-- Q33. Find the total number of orders placed by each customer.
select c.customer_name, count(o.order_id) as total_orders
from customers c
join orders o on c.Customer_ID=o.Customer_ID
group by c.customer_id
order by total_orders desc;

-- Q34. Find customers who never placed any orders
select c.customer_name, count(o.order_id) as total_orders
from customers c
left join orders o on c.Customer_ID=o.Customer_ID
group by c.customer_id
having total_orders=0;
-- or 
select c.customer_name
from customers c
left join orders o on c.Customer_ID=o.Customer_ID
where o.order_id is NULL;
-- or 
select c.customer_name
from customers c
where c.Customer_ID not in (select c.Customer_ID from orders);


-- Q35. Find the latest order date for each customer.
select c.customer_name, max(o.order_date) as latest_order_date
from customers c 
join orders o on c.Customer_ID=o.Customer_ID
group by c.customer_name;